stages:
  - build
  - deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

build-prod:
  image: docker:20.10.1
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:20.10.1-dind
  before_script:
    - docker info
  script:
    - echo "Logging into the docker registry"
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - echo "Building Dockerfile-based application..."
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - echo "Pushing the docker image to registry with name $CONTAINER_TEST_IMAGE"
    - docker push $CONTAINER_TEST_IMAGE
  environment:
    name: production
  only:
    refs:
      - master
deploy-prod:
  stage: deploy
  image:
    name: akashkaveti/base_image:latest
  before_script:
    - kubectl describe namespace "$KUBE_NAMESPACE" || kubectl create namespace "$KUBE_NAMESPACE"
    - kubectl describe service pesgerest-api-service -n "$KUBE_NAMESPACE" || kubectl create -f k8s/service.yml -n "$KUBE_NAMESPACE"
    - export IMAGE=$CONTAINER_TEST_IMAGE
    - export NAMESPACE=$KUBE_NAMESPACE
  script:
    - envsubst < k8s/ingress.yml | kubectl apply -f - -n "$KUBE_NAMESPACE"
    - envsubst < k8s/deployment.yml | kubectl apply -f - -n "$KUBE_NAMESPACE"
  environment:
    name: production
  only:
    refs:
      - master
