apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5jb20iOnsKICAgICAgICAgICAgInVzZXJuYW1lIjoiandsYXRlY2giLAogICAgICAgICAgICAicGFzc3dvcmQiOiJBZ29zdG8xMjA4MTk5NCIsCiAgICAgICAgICAgICJlbWFpbCI6Imp1YW53aWxsaW5rQGxhdGVjaGZhY3RvcnkuY29tIiwKICAgICAgICAgICAgImF1dGgiOiJaMmwwYkdGaUsyUmxjR3h2ZVMxMGIydGxiaTB6TWpreE9UQTZhVGM1VURsd1ZYbE1WV3R5UVZCT2VWWk5VM009IgogICAgCX0KICAgIH0KfQ==
